/*
 * backend/backend_error.h - 后端适配层统一错误码
 *
 * 后端只通过本文件描述平台无关的适配层失败原因，不依赖核心层错误模型。
 */

#ifndef BACKEND_ERROR_H
#define BACKEND_ERROR_H

/**
 * enum backend_error - 后端适配层操作结果
 *
 * BACKEND_ERROR_NONE 表示成功；其余值描述后端操作的技术失败原因。
 */
enum backend_error {
	BACKEND_ERROR_NONE = 0,
	BACKEND_ERROR_INVALID_ARGUMENT,
	BACKEND_ERROR_NOT_READY,
	BACKEND_ERROR_NO_MEMORY,
	BACKEND_ERROR_OPEN_FAILED,
	BACKEND_ERROR_SCAN_FAILED,
	BACKEND_ERROR_SDO_READ_FAILED,
	BACKEND_ERROR_PDO_ENTRY_LIMIT_EXCEEDED,
	BACKEND_ERROR_DC_UNSUPPORTED,
	BACKEND_ERROR_DC_CONFIG_FAILED,
	BACKEND_ERROR_PDO_MAPPING_FAILED,
	BACKEND_ERROR_PDO_IMAGE_TOO_LARGE,
	BACKEND_ERROR_PDO_OFFSET_RESOLVE_FAILED,
	BACKEND_ERROR_ACTIVATE_FAILED,
	BACKEND_ERROR_CYCLIC_RECEIVE_FAILED,
	BACKEND_ERROR_CYCLIC_SEND_FAILED,
	BACKEND_ERROR_READ_NODE_STATE_FAILED,
	BACKEND_ERROR_DEACTIVATE_FAILED,
	BACKEND_ERROR_SLAVE_RECOVER_FAILED,
};

#endif /* BACKEND_ERROR_H */
