/* Auto-generated by mo_ecat_config_gen from src/config/master.yaml */
/* DO NOT EDIT MANUALLY */

#include "mo_ecat_master_cfg.h"

const struct mo_ecat_master_config g_master_config = {
    .interface_name = "enP1p1s0",
};
