/* Auto-generated by mo_ecat_config_gen from src/config/master.yaml */
/* DO NOT EDIT MANUALLY */

#ifndef MO_ECAT_MASTER_CFG_H
#define MO_ECAT_MASTER_CFG_H

#include "config/master_config.h"

extern const struct mo_ecat_master_config g_master_config;

#endif /* MO_ECAT_MASTER_CFG_H */
