/* Auto-generated by mo_ecat_config_gen from config/master.yaml */
/* DO NOT EDIT MANUALLY */

#ifndef MO_ECAT_MASTER_CFG_H
#define MO_ECAT_MASTER_CFG_H

#include "mo_ecat/mo_ecat_master.h"

extern const struct mo_ecat_master_options g_master_options;

#endif /* MO_ECAT_MASTER_CFG_H */
