/* Auto-generated by mo_ecat_config_gen from config/master.yaml */
/* DO NOT EDIT MANUALLY */

#include "mo_ecat_master_cfg.h"

const struct mo_ecat_master_options g_master_options = {
	.interface_name = "enp0s31f6",
};
