/*
 * master_error.c - 后端错误到核心层错误的转换
 */

#include "master_error.h"

enum master_error_detail master_error_from_backend(enum backend_error error)
{
	switch (error) {
	case BACKEND_ERROR_NONE:
		return MASTER_ERROR_NONE;
	case BACKEND_ERROR_INVALID_ARGUMENT:
		return MASTER_ERROR_INVALID_ARGUMENT;
	case BACKEND_ERROR_NO_MEMORY:
		return MASTER_ERROR_NO_MEMORY;
	case BACKEND_ERROR_OPEN_FAILED:
		return MASTER_ERROR_BACKEND_OPEN_FAILED;
	case BACKEND_ERROR_SCAN_FAILED:
		return MASTER_ERROR_BUS_SCAN_FAILED;
	case BACKEND_ERROR_SDO_READ_FAILED:
		return MASTER_ERROR_READ_PDO_ASSIGNMENT_FAILED;
	case BACKEND_ERROR_PDO_ENTRY_LIMIT_EXCEEDED:
		return MASTER_ERROR_PDO_ENTRY_LIMIT_EXCEEDED;
	case BACKEND_ERROR_DC_UNSUPPORTED:
		return MASTER_ERROR_DC_UNSUPPORTED;
	case BACKEND_ERROR_DC_CONFIG_FAILED:
		return MASTER_ERROR_DC_CONFIG_FAILED;
	case BACKEND_ERROR_PDO_IMAGE_TOO_LARGE:
		return MASTER_ERROR_PDO_IMAGE_LIMIT_EXCEEDED;
	case BACKEND_ERROR_PDO_OFFSET_RESOLVE_FAILED:
		return MASTER_ERROR_PDO_OFFSET_RESOLVE_FAILED;
	case BACKEND_ERROR_PDO_MAPPING_FAILED:
		return MASTER_ERROR_PDO_MAPPING_FAILED;
	case BACKEND_ERROR_ACTIVATE_FAILED:
		return MASTER_ERROR_ACTIVATE_FAILED;
	case BACKEND_ERROR_CYCLIC_RECEIVE_FAILED:
		return MASTER_ERROR_CYCLIC_RECEIVE_FAILED;
	case BACKEND_ERROR_CYCLIC_SEND_FAILED:
		return MASTER_ERROR_CYCLIC_SEND_FAILED;
	case BACKEND_ERROR_READ_NODE_STATE_FAILED:
		return MASTER_ERROR_READ_NODE_STATE_FAILED;
	case BACKEND_ERROR_DEACTIVATE_FAILED:
		return MASTER_ERROR_DEACTIVATE_FAILED;
	case BACKEND_ERROR_NOT_READY:
	default:
		return MASTER_ERROR_INVALID_STATE;
	}
}
